import {
	Column,
	DeleteDateColumn,
	Entity,
	Index,
	JoinColumn,
	JoinTable,
	ManyToMany,
	ManyToOne,
	OneToMany,
} from 'typeorm';

import type { IsoDate } from '../../common/utils/age.util';
import { BaseEntity } from '../../common/entities/base.entity';
import { AuthIdentity } from './auth-identity.entity';
import { Category } from '../../reference/entities/category.entity';
import { Hobby } from '../../reference/entities/hobby.entity';
import { Occupation } from '../../reference/entities/occupation.entity';
import { KycStatus } from './kyc-status.enum';
import { UserPhoto } from './user-photo.entity';
import { UserRole } from './user-role.enum';
import { UserStatus } from './user-status.enum';

@Entity('users')
@Index('UQ_users_email_active', ['email'], {
	unique: true,
	where: '"deletedAt" IS NULL',
})
@Index('UQ_users_phone_active', ['phone'], {
	unique: true,
	where: '"deletedAt" IS NULL',
})
@Index('UQ_users_username_active', ['username'], {
	unique: true,
	where: '"deletedAt" IS NULL AND "username" IS NOT NULL',
})
export class User extends BaseEntity {
	@Column({ length: 80 })
	fullName!: string;

	@Column({ length: 255 })
	email!: string;

	@Column({ length: 20 })
	phone!: string;

	/**
	 * Null for accounts that only ever signed in through a federated provider.
	 * Never selected by default, so it cannot leak through an unguarded find.
	 */
	@Column({ type: 'varchar', length: 255, nullable: true, select: false })
	passwordHash!: string | null;

	@Column({ type: 'enum', enum: UserRole, default: UserRole.User })
	role!: UserRole;

	@Column({
		type: 'enum',
		enum: UserStatus,
		default: UserStatus.PendingVerification,
	})
	status!: UserStatus;

	@Column({ type: 'timestamptz', nullable: true })
	emailVerifiedAt!: Date | null;

	@Column({ type: 'timestamptz' })
	termsAcceptedAt!: Date;

	/**
	 * Nullable only because accounts predate the field; registration requires it.
	 * A profile whose age is unknown shows none rather than a guessed one.
	 */
	@Column({ type: 'date', nullable: true })
	dateOfBirth!: IsoDate | null;

	@Column({ default: false })
	pinEnabled!: boolean;

	@Column({ default: false })
	biometricsEnabled!: boolean;

	@Column({ type: 'timestamptz', nullable: true })
	lastSignedInAt!: Date | null;

	/**
	 * Last authenticated request, written at most once per touch interval by
	 * `PresenceService`. Null for an account that has not been seen since
	 * presence shipped, which reads as offline.
	 */
	@Column({ type: 'timestamptz', nullable: true })
	lastActiveAt!: Date | null;

	@DeleteDateColumn({ type: 'timestamptz' })
	deletedAt!: Date | null;

	@OneToMany(() => AuthIdentity, (identity) => identity.user)
	identities!: AuthIdentity[];

	@Column({ type: 'enum', enum: KycStatus, default: KycStatus.None })
	kycStatus!: KycStatus;

	/** Chosen during onboarding, so it is null for accounts that stopped before it. */
	@Column({ type: 'varchar', length: 32, nullable: true })
	categoryId!: string | null;

	@ManyToOne(() => Category, { nullable: true, onDelete: 'SET NULL' })
	@JoinColumn({
		name: 'categoryId',
		foreignKeyConstraintName: 'FK_users_categoryId',
	})
	category!: Category | null;

	@Column({ type: 'varchar', length: 30, nullable: true })
	username!: string | null;

	@Column({ type: 'varchar', length: 300, nullable: true })
	bio!: string | null;

	@Column({ type: 'varchar', length: 32, nullable: true })
	occupationId!: string | null;

	@ManyToOne(() => Occupation, { nullable: true, onDelete: 'SET NULL' })
	@JoinColumn({
		name: 'occupationId',
		foreignKeyConstraintName: 'FK_users_occupationId',
	})
	occupation!: Occupation | null;

	/** What the profile displays, for example "Ikeja, Lagos". */
	@Column({ type: 'varchar', length: 120, nullable: true })
	locationLabel!: string | null;

	/**
	 * Kept alongside the label because Discover ranks by distance, and
	 * re-geocoding a free text label per request would not scale.
	 */
	@Column({ type: 'double precision', nullable: true })
	latitude!: number | null;

	@Column({ type: 'double precision', nullable: true })
	longitude!: number | null;

	/**
	 * Generated by Postgres from latitude and longitude so it cannot drift from
	 * them, and indexed with GiST because discovery filters and sorts on it.
	 * Never written by the app.
	 */
	@Column({
		type: 'geography',
		spatialFeatureType: 'Point',
		srid: 4326,
		nullable: true,
		select: false,
		insert: false,
		update: false,
	})
	location!: unknown;

	@ManyToMany(() => Hobby)
	@JoinTable({
		name: 'user_hobbies',
		joinColumn: {
			name: 'userId',
			referencedColumnName: 'id',
			foreignKeyConstraintName: 'FK_user_hobbies_userId',
		},
		inverseJoinColumn: {
			name: 'hobbyId',
			referencedColumnName: 'id',
			foreignKeyConstraintName: 'FK_user_hobbies_hobbyId',
		},
	})
	hobbies!: Hobby[];

	@OneToMany(() => UserPhoto, (photo) => photo.user, { cascade: ['remove'] })
	photos!: UserPhoto[];

	get isEmailVerified(): boolean {
		return this.emailVerifiedAt !== null;
	}
}
